Schema= {'order_date': 'timestamp', 'customer_sub_status': 'string', 'customer_segment': 'string', 'site_id': 'int', 'site': 'string', 'wo_type': 'string', 'channel_group': 'string', 'channel': 'string', 'sub_channel': 'string', 'affiliate': 'string', 'etc': 'string', 'h_channel_group': 'string', 'h_channel': 'string', 'h_sub_channel': 'string', 'h_affiliate': 'string', 'h_etc': 'string', 'activity_base': 'string', 'activity': 'string', 'campaign_codes': 'string', 'campaign_descriptions': 'string', 'funnel': 'string', 'offer': 'string', 'migration_type': 'string', 'migration_net_psus': 'int', 'psu_migration': 'string', 'psu_migration_from': 'string', 'psu_migration_to': 'string', 'video_tier_migration_type': 'string', 'video_tier_migration_desc': 'string', 'chsi_tier_migration_type': 'string', 'chsi_tier_migration_desc': 'string', 'phone_tier_migration_type': 'string', 'phone_tier_migration_desc': 'string', 'homelife_tier_migration_type': 'string', 'homelife_tier_migration_desc': 'string', 'go_tier_migration_desc': 'string', 'cro_eligible': 'string', 'cro_added_date': 'timestamp', 'cro_removed_date': 'timestamp', 'cro_days': 'int', 'cro_added_date_delay': 'int', 'cro_status': 'string', 'cro_pre/post_delay': 'int', 'mdu_association_cd': 'string', 'mdu_portfolio': 'string', 'mdu_mgmt_co': 'string', 'mdu_house_assn_name': 'string', 'mdu_contract_type': 'string', 'mdu_property_tag': 'string', 'mdu_property_size': 'string', 'mdu_property_type': 'string', 'mdu_dwelling_type': 'string', 'psu_accounts': 'int', 'psus': 'int', 'psu_disconnects': 'int', 'net_revenue': 'double', 'accounts_changed': 'int', 'accounts_changed_all': 'int', 'te_segment': 'string', 'date': 'date'}


# print(Schema)

Schema2 = {'date': 'date', 'order_date': 'string', 'customer_sub_status': 'string', 'customer_segment': 'string', 'site_id': 'int', 'site': 'string', 'wo_type': 'string', 'channel_group': 'string', 'channel': 'string', 'sub_channel': 'string', 'affiliate': 'string', 'etc': 'string', 'h_channel_group': 'string', 'h_channel': 'string', 'h_sub_channel': 'string', 'h_affiliate': 'string', 'h_etc': 'string', 'activity_base': 'string', 'activity': 'string', 'campaign_codes': 'string', 'campaign_descriptions': 'string', 'funnel': 'string', 'offer': 'string', 'migration_type': 'string', 'migration_net_psus': 'int', 'psu_migration': 'string', 'psu_migration_from': 'string', 'psu_migration_to': 'string', 'video_tier_migration_type': 'string', 'video_tier_migration_desc': 'string', 'chsi_tier_migration_type': 'string', 'chsi_tier_migration_desc': 'string', 'phone_tier_migration_type': 'string', 'phone_tier_migration_desc': 'string', 'homelife_tier_migration_type': 'string', 'homelife_tier_migration_desc': 'string', 'go_tier_migration_desc': 'string', 'cro_eligible': 'string', 'cro_added_date': 'string', 'cro_removed_date': 'string', 'cro_days': 'int', 'cro_added_date_delay': 'int', 'cro_status': 'string', 'cro_pre/post_delay': 'int', 'mdu_association_cd': 'string', 'mdu_portfolio': 'string', 'mdu_mgmt_co': 'string', 'mdu_house_assn_name': 'string', 'mdu_contract_type': 'string', 'mdu_property_tag': 'string', 'mdu_property_size': 'string', 'mdu_property_type': 'string', 'mdu_dwelling_type': 'string', 'psu_accounts': 'int', 'psus': 'int', 'psu_disconnects': 'int', 'net_revenue': 'double', 'accounts_changed': 'int', 'accounts_changed_all': 'int', 'te_segment': 'string'}


# print(Schema2)

for i in Schema:
    if Schema2[i] not in Schema[i]:
        print(i, Schema[i], Schema2[i])
        print(i, Schema[i])